version: "3.9"

services:
  rabbit_mq:
    image: rabbitmq:3.8.14-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  emails:
    build: ./emails
    ports:
      - 5000:5000
    depends_on:
      - rabbit_mq
    environment:
      BROKER_HOST: rabbit_mq
      BROKER_PORT: 5672

  users:
    build: ./users
    ports:
      - 5001:5001
    depends_on:
      - rabbit_mq
      - emails
    environment:
      BROKER_HOST: rabbit_mq
      BROKER_PORT: 5672
