version: "3.9"

services: 
  database:
    build: ./database
    environment: 
      MYSQL_ROOT_PASSWORD: password
    restart: always
    ports: 
      - 3306:3306
  
  backend:
    build: ./backend
    depends_on: 
      - database
    ports: 
      - 8081:8081
    # frontend:
      # build: ./frontend
      # depends_on: 
        # - backend
      # ports: 
        # 8080:8080
      
