version: "3.9"

services: 
  database:
    build: ./database
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: products
    restart: always
    ports: 
      - 3306:3306
  
  backend:
    build: ./backend
    environment: 
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_NAME: products
      DATABASE_USER: root
      DATABASE_PASSWORD: password
    depends_on: 
      - database
    ports: 
      - 8081:8081

  frontend:
    build: ./frontend
    depends_on: 
      - backend
    ports: 
      - 8080:8080
